title: 石文芝的主页
description: 一个现代化的个人主页
author: 石文芝
email: your.email@example.com
baseurl: "/swz"
url: "https://susunaKaa.github.io"
twitter_username: yourtwitter
github_username: susunaKaa
linkedin_username: yourlinkedin

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
